databases:
  - name: kidd
    ipAllowList: []
    databaseName: my_database
    user: my_app_render

services:
  - type: web
    name: my_database
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kidd
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false